### ISSUE TITLE
My Account link is not working

### ISSUE THREAD

**Issue by ratneshp0** [shopizer-ecommerce/shopizer#67] opened 2016-03-03 14:05 UTC
When I click on My Account link after I login, it takes me to the dashboard.html page. There I am provided with three links like My Account, Billing and shipping address and one more. When I click on the My account link on the dashboard.html it takes me to nowhere. I checked the code, it seems its trying to get some customer option name and customer option code from the DB. I am not sure how these would be populated. I could see some option in the admin panel and tried to put some name and value there but it went in vain. Any idea how this My Account link works.

Thanks,
Ratnesh

**Comment by ratneshp0** [comment] 2016-03-10 10:15
Can anybody help on this.

**Comment by ratneshp0** [comment] 2016-03-10 19:44
Yes I am using 2.0.3

**Comment by ratneshp0** [comment] 2016-03-12 05:03
Please let me know your finding about my account link issue.

**Comment by umeshawasthi** [comment] 2016-03-12 20:19
@ratneshp0 
My account section is only redirecting you to main dashboard , if you do not want it you can always customize this section.
This is not a bug, closing this ticket,

**Closed by umeshawasthi** 2016-03-12 20:19 UTC

**Comment by ratneshp0** [comment] 2016-03-13 06:04
But even in the dashboard if you click on my account it goes nowhere. May
be it calso he customized. Can you please help me on this.
